# Generated by Django 5.2.3 on 2025-06-26 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('F', 'FREE'), ('B', 'BASIC'), ('S', 'STANDARD'), ('P', 'PREMIUM'), ('PP', 'PREMIUM PLUS')])),
            ],
        ),
    ]
