# Generated by Django 5.2.3 on 2025-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
