# Generated by Django 5.2.3 on 2025-06-26 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_store_trialcertificate_trialreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.AddField(
            model_name='trialcertificate',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trialcertificate',
            name='certificate_number',
            field=models.CharField(max_length=100),
        ),
    ]
