# Generated by Django 5.2.3 on 2025-06-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_remove_store_location_trialcertificate_issued_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variety',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='variety',
            new_name='content',
        ),
    ]
